framework:
    cache:
        pools:
            crm.cache:
                adapter: cache.adapter.filesystem

when@prod:
    framework:
        cache:
            pools:
                crm.cache:
                    adapter: cache.adapter.redis