nelmio_api_doc:
    documentation:
        info:
            title: ReklamHUB API v1
            description: This is REST API ReklamHUB!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/doc$) # Accepts routes under /api except /api/doc
    models:
        names:
            - { alias: Pipeline, type: App\CRM\DTO\Pipeline\PipelineDTO }
            - { alias: PipelineDetail, type: App\CRM\DTO\Pipeline\PipelineDetailDTO }
            - { alias: PipelineListResponse, type: App\CRM\DTO\OpenAPI\Pipeline\PipelineListResponseDTO }
            - { alias: PipelineListDetailResponse, type: App\CRM\DTO\OpenAPI\Pipeline\PipelineListDetailResponseDTO }
            - { alias: PipelineRequest, type: App\CRM\DTO\OpenAPI\Pipeline\PipelineRequestDTO }
            
            - { alias: StageUI, type: App\CRM\DTO\Stage\StageUIDTO }
            - { alias: Stage, type: App\CRM\DTO\Stage\StageDTO }
            - { alias: StageRequest, type: App\CRM\DTO\OpenAPI\Stage\StageRequestDTO }
            - { alias: StageRequestEdit, type: App\CRM\DTO\OpenAPI\Stage\StageRequestEditDTO }
            - { alias: StageRequestPosition, type: App\CRM\DTO\OpenAPI\Stage\StageRequestPositionDTO }
            - { alias: StageKanban, type: App\CRM\DTO\Stage\StageKanbanDTO }

            - { alias: Kanban, type: App\CRM\DTO\KanbanDTO }

            - { alias: Lead, type: App\CRM\DTO\Lead\LeadDTO }
            - { alias: LeadDetail, type: App\CRM\DTO\Lead\LeadDetailDTO }
            - { alias: LeadKanban, type: App\CRM\DTO\Lead\LeadKanbanDTO }
            - { alias: LeadUpdateRequest, type: App\CRM\DTO\OpenAPI\Lead\LeadUpdateRequestDTO }
            - { alias: LeadRequest, type: App\CRM\DTO\OpenAPI\Lead\LeadRequestDTO }
            - { alias: LeadListResponse, type: App\CRM\DTO\OpenAPI\Lead\LeadListResponseDTO }
            
            - { alias: Client, type: App\CRM\DTO\Client\ClientDTO }
            - { alias: ClientDetail, type: App\CRM\DTO\Client\ClientDetailDTO }
            - { alias: ClientListResponse, type: App\CRM\DTO\OpenAPI\Client\ClientListResponseDTO }
            - { alias: ClientRequest, type: App\CRM\DTO\OpenAPI\Client\ClientRequestDTO }

            - { alias: Contact, type: App\CRM\DTO\Contact\ContactDTO }
            - { alias: ContactListResponse, type: App\CRM\DTO\OpenAPI\Contact\ContactListResponseDTO }
            - { alias: ContactRequest, type: App\CRM\DTO\OpenAPI\Contact\ContactRequestDTO }

            - { alias: Message, type: App\CRM\DTO\LeadMessages\MessageDTO }
            - { alias: LeadMessagesListResponse, type: App\CRM\DTO\OpenAPI\LeadMessages\LeadMessagesListResponseDTO }
            - { alias: LeadMessagesRequest, type: App\CRM\DTO\OpenAPI\LeadMessages\LeadMessagesRequestDTO }
            - { alias: LeadMessageEditRequest, type: App\CRM\DTO\OpenAPI\LeadMessages\LeadMessageEditRequestDTO }
