version: "3.9"

services:
  node:
    image: node:22-alpine
    container_name: symfony_node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0