<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260713071530 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE client (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, inn VARCHAR(12) DEFAULT NULL, field_of_activity VARCHAR(50) DEFAULT NULL, website VARCHAR(50) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, city VARCHAR(50) DEFAULT NULL, channel VARCHAR(50) DEFAULT NULL, date_create TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, secondname VARCHAR(100) NOT NULL, thirdname VARCHAR(100) DEFAULT NULL, position VARCHAR(100) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, messenger VARCHAR(100) DEFAULT NULL, note VARCHAR(255) DEFAULT NULL, date_create TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C62E63819EB6921 ON contact (client_id)');
        $this->addSql('CREATE TABLE lead (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, budget DOUBLE PRECISION DEFAULT 0 NOT NULL, product VARCHAR(50) DEFAULT NULL, source VARCHAR(50) DEFAULT NULL, next_action VARCHAR(50) DEFAULT NULL, date_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_next_action TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, comment VARCHAR(255) DEFAULT NULL, status VARCHAR(255) NOT NULL, responsible_id INT DEFAULT NULL, client_id INT DEFAULT NULL, stage_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_289161CB602AD315 ON lead (responsible_id)');
        $this->addSql('CREATE INDEX IDX_289161CB19EB6921 ON lead (client_id)');
        $this->addSql('CREATE INDEX IDX_289161CB2298D193 ON lead (stage_id)');
        $this->addSql('CREATE TABLE lead_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message VARCHAR(4096) NOT NULL, date_send TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lead_id INT DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF736C1155458D ON lead_message (lead_id)');
        $this->addSql('CREATE INDEX IDX_EF736C11A76ED395 ON lead_message (user_id)');
        $this->addSql('CREATE TABLE pipeline (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE stage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, color VARCHAR(50) NOT NULL, sequence INT DEFAULT NULL, pipeline_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C27C9369E80B93 ON stage (pipeline_id)');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E63819EB6921 FOREIGN KEY (client_id) REFERENCES client (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lead ADD CONSTRAINT FK_289161CB602AD315 FOREIGN KEY (responsible_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lead ADD CONSTRAINT FK_289161CB19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lead ADD CONSTRAINT FK_289161CB2298D193 FOREIGN KEY (stage_id) REFERENCES stage (id)');
        $this->addSql('ALTER TABLE lead_message ADD CONSTRAINT FK_EF736C1155458D FOREIGN KEY (lead_id) REFERENCES lead (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lead_message ADD CONSTRAINT FK_EF736C11A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stage ADD CONSTRAINT FK_C27C9369E80B93 FOREIGN KEY (pipeline_id) REFERENCES pipeline (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE contact DROP CONSTRAINT FK_4C62E63819EB6921');
        $this->addSql('ALTER TABLE lead DROP CONSTRAINT FK_289161CB602AD315');
        $this->addSql('ALTER TABLE lead DROP CONSTRAINT FK_289161CB19EB6921');
        $this->addSql('ALTER TABLE lead DROP CONSTRAINT FK_289161CB2298D193');
        $this->addSql('ALTER TABLE lead_message DROP CONSTRAINT FK_EF736C1155458D');
        $this->addSql('ALTER TABLE lead_message DROP CONSTRAINT FK_EF736C11A76ED395');
        $this->addSql('ALTER TABLE stage DROP CONSTRAINT FK_C27C9369E80B93');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE lead');
        $this->addSql('DROP TABLE lead_message');
        $this->addSql('DROP TABLE pipeline');
        $this->addSql('DROP TABLE stage');
    }
}
