<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260809172606 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE client_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, data JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_id INT DEFAULT NULL, manager_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7587343619EB6921 ON client_history (client_id)');
        $this->addSql('CREATE INDEX IDX_75873436783E3463 ON client_history (manager_id)');
        $this->addSql('CREATE TABLE email_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, client_id INT DEFAULT NULL, contact_id INT DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6FB488319EB6921 ON email_log (client_id)');
        $this->addSql('CREATE INDEX IDX_6FB4883E7A1254A ON email_log (contact_id)');
        $this->addSql('CREATE INDEX IDX_6FB4883A76ED395 ON email_log (user_id)');
        $this->addSql('CREATE TABLE lead_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, data JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, lead_id INT DEFAULT NULL, manager_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7E742C2555458D ON lead_history (lead_id)');
        $this->addSql('CREATE INDEX IDX_7E742C25783E3463 ON lead_history (manager_id)');
        $this->addSql('ALTER TABLE client_history ADD CONSTRAINT FK_7587343619EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE client_history ADD CONSTRAINT FK_75873436783E3463 FOREIGN KEY (manager_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE email_log ADD CONSTRAINT FK_6FB488319EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE email_log ADD CONSTRAINT FK_6FB4883E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id)');
        $this->addSql('ALTER TABLE email_log ADD CONSTRAINT FK_6FB4883A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE lead_history ADD CONSTRAINT FK_7E742C2555458D FOREIGN KEY (lead_id) REFERENCES lead (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lead_history ADD CONSTRAINT FK_7E742C25783E3463 FOREIGN KEY (manager_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE lead_message DROP CONSTRAINT fk_ef736c1155458d');
        $this->addSql('ALTER TABLE lead_message ADD CONSTRAINT FK_EF736C1155458D FOREIGN KEY (lead_id) REFERENCES lead (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE client_history DROP CONSTRAINT FK_7587343619EB6921');
        $this->addSql('ALTER TABLE client_history DROP CONSTRAINT FK_75873436783E3463');
        $this->addSql('ALTER TABLE email_log DROP CONSTRAINT FK_6FB488319EB6921');
        $this->addSql('ALTER TABLE email_log DROP CONSTRAINT FK_6FB4883E7A1254A');
        $this->addSql('ALTER TABLE email_log DROP CONSTRAINT FK_6FB4883A76ED395');
        $this->addSql('ALTER TABLE lead_history DROP CONSTRAINT FK_7E742C2555458D');
        $this->addSql('ALTER TABLE lead_history DROP CONSTRAINT FK_7E742C25783E3463');
        $this->addSql('DROP TABLE client_history');
        $this->addSql('DROP TABLE email_log');
        $this->addSql('DROP TABLE lead_history');
        $this->addSql('ALTER TABLE lead_message DROP CONSTRAINT FK_EF736C1155458D');
        $this->addSql('ALTER TABLE lead_message ADD CONSTRAINT fk_ef736c1155458d FOREIGN KEY (lead_id) REFERENCES lead (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
